repository:
  description: description of the repo
  private: true
labels:
  include:
    - name: test1
      color: '#d73a4a'
      description: test1
    - name: tes8787897987489798
      color: '#a2ee8f'
      description: test4
