repository:
  description: description of the repo
  private: false
labels:
  include:
    - name: test1
      color: '#d73a4a'
      description: test1
    - name: test2
      color: '#a2eeef'
      description: test2
